### ISSUE TITLE
Initial User Experience needs lots of work

### ISSUE THREAD

**Issue by karlunho-datastax** [CassioML/cassio#1]
- Need to improve homepage
- Need to improve Prompt Template example.

Walkthrough of user experience - https://drive.google.com/file/d/1w5otdPItPGA9tDo-j282P1UCdDT6z2og/view

**Comment by hemidactylus** [comment]
This belongs to the cassio-website repo.
- Closing the issue here
- Moving it [there](https://github.com/CassioML/cassio-website/issues/25) (for subsequent splitting in several sub-task, easier-to-track issues)
