### ISSUE TITLE
Implement MMR retrieval at cassIO level

### ISSUE THREAD

**Issue by hemidactylus** [CassioML/cassio#28]
It might make sense for the cassIO VectorTable class to offer its own MMR implementation.

(Currently for the langchain integration case this is done at langchain level, but arguably the right place is cassIO).

**Comment by karlunho-datastax** [comment]
Let's look at LlamaIndex first before trying to do this refactoring.

**Comment by hemidactylus** [comment]
Right, Llama has its own implementation and for now we'll piggyback on it :)

**Comment by xingh** [comment]
Langchain also has a selector https://python.langchain.com/docs/modules/model_io/prompts/example_selectors/mmr
