### ISSUE TITLE
[Epic] Implement support for LlamaIndex

### ISSUE THREAD

**Issue by karlunho-datastax** [CassioML/cassio#29]
CassIO currently supports Langchain. We should add support for LlamaIndex next.

Integration options:
Vector Store - https://gpt-index.readthedocs.io/en/latest/how_to/integrations/vector_stores.html
Index Stores - https://gpt-index.readthedocs.io/en/latest/how_to/storage/index_stores.html

**Comment by hemidactylus** [comment]
I suggest this should be broken down into more manageable better-defined units, such as "Llamaindex: Cassandra backend for [VectorStoreIndex interface](https://gpt-index.readthedocs.io/en/latest/how_to/integrations/vector_stores.html)", plus others.

**Comment by karlunho-datastax** [comment]
Agreed - I've added a new label called "Epic" to help differentiated very large items VS things that are actionable.

**Comment by xingh** [comment]
This task has been broken up but wanted to add context in the parent task

*LllamaIndex - Complete

- Details
  - CassIO currently supports Langchain. We should add support for LlamaIndex next.
  - Integration options:
    - Vector Store
    - Index Stores
    - Document Store (KV Store)
  - suggest this should be broken down into more manageable better-defined units, such as "Llamaindex: Cassandra backend for VectorStoreIndex interface", plus others.
- Outcome
  - #79 
  - #38 
  - #78
  - Create examples to use LllamaIndex - Index Data, use Chainlit UI to ask questions
- References
  - https://gpt-index.readthedocs.io/en/stable/core_modules/data_modules/storage/docstores.html
  - https://gpt-index.readthedocs.io/en/latest/how_to/storage/index_stores.html 
  - https://gpt-index.readthedocs.io/en/latest/how_to/integrations/vector_stores.html
