### ISSUE TITLE
Update Langchain docs so that it reflects the updated chathistory capabilities of Cassandra & the ability to use AstraDB

### ISSUE THREAD

**Issue by karlunho-datastax** [CassioML/cassio#3]
Currently, the docs of the langchain integration looks very basic, and doesn't reflect vector search or CassIO:

https://python.langchain.com/docs/modules/memory/integrations/cassandra_chat_message_history
https://python.langchain.com/docs/ecosystem/integrations/cassandra
https://github.com/hwchase17/langchain/blob/master/langchain/memory/chat_message_histories/cassandra.py

It is also possible to create a version of the chat that discusses the managed version of Cassandra (AstraDB)

https://python.langchain.com/docs/modules/memory/integrations/motorhead_memory_managed

Other places that documentation & integration is missing:
https://python.langchain.com/docs/modules/data_connection/retrievers/
https://python.langchain.com/docs/modules/data_connection/text_embedding/

A suggestions is to drop a link to the CassIO website.

**Comment by hemidactylus** [comment]
Good suggestion!

Postponed until the vector-based memory PR is (submitted and then) accepted.

**Comment by karlunho-datastax** [comment]
Appears to be completed, but it seems like there is some inconsistency on version for langchain vector store and chat history
