### ISSUE TITLE
Create utility to determine thresholds for setting vector search relevancy thresholds

### ISSUE THREAD

**Issue by karlunho-datastax** [CassioML/cassio#37]
Currently, there is no easy way to determine the distance thresholds for relevancy for Nearest Neighbor search. We need a tool that can help at least "visually" help determine a good cutoff for relevancy (see : https://towardsdatascience.com/k-nearest-neighbors-knn-for-anomaly-detection-fdf8ee160d13)

**Comment by karlunho-datastax** [comment]
Eric will take the lead on this project, with Elena to also contribute.

- Ideally a python notebook with visualization
- Possibly use Tensorboard for visualization


Side task - investigate visualization for LLMs in Tensorboard.

**Comment by erichare** [comment]
https://colab.research.google.com/drive/1iiV6VAMGf28TwAlBuLpwfxzS0DSxz7be

Tensorboard visualization pending

**Comment by erichare** [comment]
[vector_similarity_thresholding.ipynb.zip](https://github.com/CassioML/cassio/files/12296370/vector_similarity_thresholding.ipynb.zip)

Will add to Colab after a bit of TLC but, this implements an algorithm along the lines of what we talked about - basically, we use the distribution of distances between the outliers across the variables of interest as a threshold. We then take a new row (i.e., a question), compute the embedding, compute distances to all other rows, and use that derived threshold to identify ones that fall with a range of k in terms of distance - effectively thresholding out the ones that are "too far" apart, where too far is based on that determination from the anomaly detection algorithm.

**Comment by erichare** [comment]
Google Colab Link: https://colab.research.google.com/drive/1iiV6VAMGf28TwAlBuLpwfxzS0DSxz7be
GitHub Link: https://github.com/riptano/vector-aiml-experiments/blob/main/vector-similarity-thresholding/thresholding.ipynb
