### ISSUE TITLE
Create example of CassIO working with FLARE

### ISSUE THREAD

**Issue by karlunho-datastax** [CassioML/cassio#4]
https://python.langchain.com/docs/modules/chains/additional/flare

https://arxiv.org/abs/2305.06983

**Comment by karlunho-datastax** [comment]
Underneath the hood, it seems like FLARE / AutoGPT / etc can use any vector store out of box without needing a custom CQLTool being implemented. We should just implement samples using the Vector Store abstraction

**Comment by karlunho-datastax** [comment]
In progress - https://github.com/hemidactylus/langchain-flare-pdf-qa-demo

**Comment by karlunho-datastax** [comment]
@hemidactylus - I have a few requests for the flare demo

- [ ] separate the metadata blob into separate fields and put a secondary index on those fields ?
- [ ] In addition to source and page, can you please add an "chunk number" as a separate metadata field ?

**Comment by xingh** [comment]
- Details
  - See above
- Outcome
  - Complete Langchain FLARE implementation 
  - Create llamaindex FLARE implementation
  - Create ui with Chainlit (supports langchain and llamaindex)
- References
  - https://python.langchain.com/docs/modules/chains/additional/flare
  - https://arxiv.org/abs/2305.06983
  - https://github.com/hemidactylus/langchain-flare-pdf-qa-demo
  - https://gpt-index.readthedocs.io/en/latest/examples/query_engine/flare_query_engine.html

**Comment by hemidactylus** [comment]
My goal (not necessarily at odds with the above chainlit suggestion) is to (also) have a fastAPI+React client/server that can be started in gitpod "all in one click". This to have at least a full "prod-level" LLM e2e app.
(and except that the UI is ugly and the missing gitpod part, the api+react client scaffold is there already).
I'll come back to this demo next week (but we can discuss any time).

**Comment by xingh** [comment]
There are other REACT frameworks we can use to make it look pretty.

**Comment by hemidactylus** [comment]
I'd be happy to welcome them :) "pretty UIs" are not my daily thing (...and it shows, lol)

**Comment by hemidactylus** [comment]
the flare demo repo should be moved to this org (it's in my personal github, does not make much sense). Any objection?

**Comment by hemidactylus** [comment]
Update: repo moved to https://github.com/CassioML/langchain-flare-pdf-qa-demo .
I will look at the "optional clustering" support throughout the integrations during the week.
(it'll have to be a PR but this demo could work on a preview branch for a while).

**Comment by hemidactylus** [comment]
Clustering support is there. Demo completed, opens smoothly in gitpod and overall looks nice to me.

https://github.com/CassioML/langchain-flare-pdf-qa-demo
