### ISSUE TITLE
Create Composable Prompt Templates for RAG

### ISSUE THREAD

**Issue by karlunho-datastax** [CassioML/cassio#41]
Prompting the LLM with the right prompt template is important for the LLM to make sense to the content from Vector search. Important items include:

- [ ] Appropriate Directives
- [ ] Proper content layout (User Context section, Memory section, Index data section, etc)
- [ ] Tools to ensure that prompt fits within the context window

**Comment by xingh** [comment]
look into semantic kernel and langchain as starting points - sem kernel - their composeable skill / function system is superior to langchain
