### ISSUE TITLE
Investigate how to use filtered Vector Search to improve search results

### ISSUE THREAD

**Issue by karlunho-datastax** [CassioML/cassio#53]
Vector Search - specifically k nearest neighbor - is very sensitive to outliers. Filtered vector search gives the ability to reduce the search space prior to performing vector search. This is being advertised in Pinecone's marketing materials significantly, so we need to figure out how to perform this. Tooling such as langchain actually don't make it possible to do filtered vector search.

**Comment by xingh** [comment]
@hemidactylus new metadata search I think can help - maybe its the first version of it
