### ISSUE TITLE
Setup benchmark to measure precision@K and recall@K to compare ANN with KNN

### ISSUE THREAD

**Issue by karlunho-datastax** [CassioML/cassio#64]
similar to [ this issue](https://github.com/CassioML/cassio/issues/56) but focused on comparing ANN with KNN

**Comment by erichare** [comment]
[ann_v_knn.ipynb.zip](https://github.com/CassioML/cassio/files/12244947/ann_v_knn.ipynb.zip)

Very preliminary notebook implementing some concepts here

**Comment by erichare** [comment]
Google Colab Link: https://colab.research.google.com/drive/1yaG_MtoLUVDVOUJ7up8FfryRMMB8-onW
GitHub Link: https://github.com/riptano/vector-aiml-experiments/blob/main/ann-vs-knn/comparison.ipynb

**Comment by karlunho-datastax** [comment]
@ElenaKusevska To work with @erichare to test out AstraDB and PineCone
