### ISSUE TITLE
Create example notebook for DSE launch

### ISSUE THREAD

**Issue by karlunho-datastax** [CassioML/cassio#65]
Existing Notebooks on the CassIO website focuses on integrating against astraDB. We need an example notebook that steps through how to run against DSE, and ideally a opensource model like Llama 2.

**Comment by karlunho-datastax** [comment]
I'll assign to Alejandro after he accepts the invite.

**Comment by karlunho-datastax** [comment]
@acantarero Any update on this ticket ?

**Comment by acantarero** [comment]
all open DSE work that was on my plate is going to move to Brian Mortimer.  I'm meeting with him later today. I'll point him at this ticket.

**Comment by karlunho-datastax** [comment]
Add Brian to the github and re-assign. Thanks.

**Comment by bhmortim** [comment]
please assign to me

**Comment by hemidactylus** [comment]
Closing as out of scope (for this cassio repo) and anyway lack of activity - I am sure this progress, if the initiative is ongoing, is tracked elsewhere at this point :)
