### ISSUE TITLE
Create CassIO Integration with Airbyte

### ISSUE THREAD

**Issue by karlunho-datastax** [CassioML/cassio#68]
Do something like pinecone

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-langchain/integration_tests/pinecone_integration_test.py

**Comment by xingh** [comment]
Technically we should already have connectivity. Airbyte's connectivity is with Langchain as a destination, so we just need an integration test. Airbyte runs docker containers under the hood so it allows for parallel processing by spinning up different containers. It would be nice to do a load test and see how well Cassio responds.

**Comment by xingh** [comment]
- Details
  - Do something like pinecone ( make sure it works with Langchain ) 
  - Airbyte has a massive ecosystem of connectors. Main components are sources, sinks, and processors, all of which execute on dockerized processes, which is how it scales. 
  - It also has support for streaming , which means there is a deeper integration with Astra Streams potentially. 
- Outcome
  - Validate Airbyte Integration with Langchain powered by Cassio Vector Store 
  - LATER Create Airbyte Connector for Astra / Cassandra / Vector Search
    - Source - Cassandra source
    - Sink - Cassandra sink, Cassandra Vector Sink
    - Processor - Cassio / Embedding Processor 
- References
  - https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-langchain/integration_tests/pinecone_integration_test.py
  - https://docs.airbyte.com/understanding-airbyte/airbyte-protocol#common-interface-methods
  - https://docs.airbyte.com/understanding-airbyte/supported-data-types/
  - https://docs.airbyte.com/understanding-airbyte/airbyte-protocol-docker
