### ISSUE TITLE
Cassio integration with Supabase

### ISSUE THREAD

**Issue by karlunho-datastax** [CassioML/cassio#69]

**Comment by xingh** [comment]
Supabase is a wrapper to several open source projects 

Kong wraps GoTrue, Postgrest, Realtime, Storage, pg-meta, Functions , and recently pgVector plugin on postgers . All these work on top of Postgres

![image](https://github.com/CassioML/cassio/assets/400761/54c92881-9f4f-46ee-90fa-61a0b2afce8f)

Let's clarify what we mean by integration with Supabase. We use Supabase on a few projects, and there's a list of "works well with Supabase" but they usually run on top of Supabase such as nocode builders, etc. 

Potential integration could be - we bind to "Realtime" function which watches for data changes and sends it to the user experience to push data to Cassio and have it immediately indexed and available.

**Comment by xingh** [comment]
- Details
  - There are 7 categories of "Integrations" and these are the categories that make sense to explore in this order. 
    - High Potential
      - API
        - Mirroring Supabase Data / Extending what's in Supabase with what is in Astra 
    - Low Potential
      - Caching
        - Sync w/ Astra for high speed high availablity with what is in Supabase
      - Likely separate concern - would make sense to look integrating with what Supabase integrates with now 
        - Auth
        - Data Platform
        - Low-Code
        - DevTools 
- Outcome
  - Need to clarify strategy in general to work with Supabase 
  - Identify one or two categories to focus on
  - New Repository called "cassio-supabase"
- References
  - https://supabase.com/partners/integrations
