### ISSUE TITLE
Integration into OpenAI Cookbook

### ISSUE THREAD

**Issue by karlunho-datastax** [CassioML/cassio#74]
See existing cookbooks:

https://github.com/openai/openai-cookbook/tree/main/examples/vector_databases

Also, add/PR to https://platform.openai.com/docs/guides/embeddings/limitations-risks#expander-2 documentation

**Comment by xingh** [comment]
@hemidactylus is working on this but adding some research / notes - feel free to take or leave any of the suggestions

- Details
  - OpenAI Cookbook has sample code for 14 different Vector Stores
  - These are mostly Python notebooks with some Docker-Composes that run a service if it's open source.
  - Like we need to copy Pinecone's example and make it work with Vector Search
  - Some examples use Langchain, others are vanilla Python + OpenAI
- Outcome
  - New Folder in a forked copy of the openai-cookbook repository "cassandra-vector" or "astra-vector" or "cassio"
    - README.md
      - Step by Step Tutorial with Background Info / Setup etc. for Astra / OpenAI 
    - Notebook: General QA (Python + OpenAI)
    - Notebook: Retrieval Augmentation (Langchain + Python + OpenAI)
  - Pull Request Submitted
- References
  - https://github.com/CassioML/cassio/issues/74
  - https://github.com/openai/openai-cookbook/tree/main/examples/vector_databases
  - https://github.com/openai/openai-cookbook/pulls
